version: '3'
services:
  postgresql_db:
    restart: always
    container_name: drf_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    volumes:
      - yatube_api_data:/var/lib/postgresql/data
    ports:
      - '${PORT}:${PORT}'
    networks:
      - yatube_api_network
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    networks:
      - yatube_api_network
    env_file:
      - .env
  backend:
    restart: always
    container_name: drf_backend
    image: gideonravenor1/api_yamdb:1.0
    build:
      context: ../api_yamdb
      dockerfile: Dockerfile
    volumes:
      - ../api_yamdb:/app
      - static_volume:/app/staticfiles
    command: bash -c "cd /app &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 --workers 3 api_yamdb.wsgi:application"
    depends_on:
      - postgresql_db
    networks:
      - yatube_api_network
    ports:
      - '8000:8000'
    env_file:
      - .env
  nginx:
    restart: always
    container_name: nginx_drf
    image: nginx:latest
    depends_on:
      - backend
      - pgadmin
    networks:
      - yatube_api_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - '80:80'
networks:
  yatube_api_network:

volumes:
  yatube_api_data:
  static_volume: