version: '3'
services:
  postgresql_db:
    restart: always
    container_name: drf_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - yatube_api_data:/var/lib/postgresql/data
    expose:
      - '${DB_PORT}'
    networks:
      - yatube_api_network
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - '5050'
    networks:
      - yatube_api_network
    env_file:
      - .env
  backend:
    restart: always
    container_name: drf_backend
    image: gideonravenor1/yamdb_final:latest
    volumes:
      - static_volume:/app/staticfiles
    command: bash -c "cd /app && gunicorn --bind 0.0.0.0:8000 --workers 3 api_yamdb.wsgi:application"
    depends_on:
      - postgresql_db
    networks:
      - yatube_api_network
    expose:
      - '8000'
    env_file:
      - .env
  nginx:
    restart: always
    container_name: nginx_drf
    image: nginx:1.8-alpine
    depends_on:
      - backend
      - pgadmin
    networks:
      - yatube_api_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - '80:80'
networks:
  yatube_api_network:

volumes:
  yatube_api_data:
  static_volume: